//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillsAndTasksDesktopClient.MBService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksDesktopClient.MBService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksDesktopClient.MBService.Skill))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksDesktopClient.MBService.Task))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksDesktopClient.MBService.UserSkill))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksDesktopClient.MBService.DatabaseData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksDesktopClient.MBService.Skill[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksDesktopClient.MBService.Task[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksDesktopClient.MBService.UserSkill[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksDesktopClient.MBService.User[]))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Skill", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    public partial class Skill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssignedToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFinishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModificationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssignedTo {
            get {
                return this.AssignedToField;
            }
            set {
                if ((this.AssignedToField.Equals(value) != true)) {
                    this.AssignedToField = value;
                    this.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFinished {
            get {
                return this.IsFinishedField;
            }
            set {
                if ((this.IsFinishedField.Equals(value) != true)) {
                    this.IsFinishedField = value;
                    this.RaisePropertyChanged("IsFinished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModificationDate {
            get {
                return this.ModificationDateField;
            }
            set {
                if ((this.ModificationDateField.Equals(value) != true)) {
                    this.ModificationDateField = value;
                    this.RaisePropertyChanged("ModificationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((this.ModifiedByField.Equals(value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskName {
            get {
                return this.TaskNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskNameField, value) != true)) {
                    this.TaskNameField = value;
                    this.RaisePropertyChanged("TaskName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSkill", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    public partial class UserSkill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SkillIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SkillId {
            get {
                return this.SkillIdField;
            }
            set {
                if ((this.SkillIdField.Equals(value) != true)) {
                    this.SkillIdField = value;
                    this.RaisePropertyChanged("SkillId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseData", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    public partial class DatabaseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SkillsAndTasksDesktopClient.MBService.Skill[] SkillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SkillsAndTasksDesktopClient.MBService.Task[] TasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SkillsAndTasksDesktopClient.MBService.UserSkill[] UserSkillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SkillsAndTasksDesktopClient.MBService.User[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkillsAndTasksDesktopClient.MBService.Skill[] Skills {
            get {
                return this.SkillsField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillsField, value) != true)) {
                    this.SkillsField = value;
                    this.RaisePropertyChanged("Skills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkillsAndTasksDesktopClient.MBService.Task[] Tasks {
            get {
                return this.TasksField;
            }
            set {
                if ((object.ReferenceEquals(this.TasksField, value) != true)) {
                    this.TasksField = value;
                    this.RaisePropertyChanged("Tasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkillsAndTasksDesktopClient.MBService.UserSkill[] UserSkills {
            get {
                return this.UserSkillsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSkillsField, value) != true)) {
                    this.UserSkillsField = value;
                    this.RaisePropertyChanged("UserSkills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkillsAndTasksDesktopClient.MBService.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MBService.IMBService")]
    public interface IMBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createAccount", ReplyAction="http://tempuri.org/IMBService/createAccountResponse")]
        SkillsAndTasksDesktopClient.MBService.Response createAccount(SkillsAndTasksDesktopClient.MBService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createAccount", ReplyAction="http://tempuri.org/IMBService/createAccountResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> createAccountAsync(SkillsAndTasksDesktopClient.MBService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createSkill", ReplyAction="http://tempuri.org/IMBService/createSkillResponse")]
        SkillsAndTasksDesktopClient.MBService.Response createSkill(SkillsAndTasksDesktopClient.MBService.Skill skill);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createSkill", ReplyAction="http://tempuri.org/IMBService/createSkillResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> createSkillAsync(SkillsAndTasksDesktopClient.MBService.Skill skill);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/deleteSkill", ReplyAction="http://tempuri.org/IMBService/deleteSkillResponse")]
        SkillsAndTasksDesktopClient.MBService.Response deleteSkill(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/deleteSkill", ReplyAction="http://tempuri.org/IMBService/deleteSkillResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> deleteSkillAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/updateSkill", ReplyAction="http://tempuri.org/IMBService/updateSkillResponse")]
        SkillsAndTasksDesktopClient.MBService.Response updateSkill(SkillsAndTasksDesktopClient.MBService.Skill skill);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/updateSkill", ReplyAction="http://tempuri.org/IMBService/updateSkillResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> updateSkillAsync(SkillsAndTasksDesktopClient.MBService.Skill skill);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createTask", ReplyAction="http://tempuri.org/IMBService/createTaskResponse")]
        SkillsAndTasksDesktopClient.MBService.Response createTask(SkillsAndTasksDesktopClient.MBService.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createTask", ReplyAction="http://tempuri.org/IMBService/createTaskResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> createTaskAsync(SkillsAndTasksDesktopClient.MBService.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/deleteTask", ReplyAction="http://tempuri.org/IMBService/deleteTaskResponse")]
        SkillsAndTasksDesktopClient.MBService.Response deleteTask(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/deleteTask", ReplyAction="http://tempuri.org/IMBService/deleteTaskResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> deleteTaskAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/updateTask", ReplyAction="http://tempuri.org/IMBService/updateTaskResponse")]
        SkillsAndTasksDesktopClient.MBService.Response updateTask(SkillsAndTasksDesktopClient.MBService.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/updateTask", ReplyAction="http://tempuri.org/IMBService/updateTaskResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> updateTaskAsync(SkillsAndTasksDesktopClient.MBService.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createUserSkill", ReplyAction="http://tempuri.org/IMBService/createUserSkillResponse")]
        SkillsAndTasksDesktopClient.MBService.Response createUserSkill(SkillsAndTasksDesktopClient.MBService.UserSkill us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createUserSkill", ReplyAction="http://tempuri.org/IMBService/createUserSkillResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> createUserSkillAsync(SkillsAndTasksDesktopClient.MBService.UserSkill us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/deleteUserSkill", ReplyAction="http://tempuri.org/IMBService/deleteUserSkillResponse")]
        SkillsAndTasksDesktopClient.MBService.Response deleteUserSkill(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/deleteUserSkill", ReplyAction="http://tempuri.org/IMBService/deleteUserSkillResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> deleteUserSkillAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/updateUserSkill", ReplyAction="http://tempuri.org/IMBService/updateUserSkillResponse")]
        SkillsAndTasksDesktopClient.MBService.Response updateUserSkill(SkillsAndTasksDesktopClient.MBService.UserSkill us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/updateUserSkill", ReplyAction="http://tempuri.org/IMBService/updateUserSkillResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> updateUserSkillAsync(SkillsAndTasksDesktopClient.MBService.UserSkill us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/loginExists", ReplyAction="http://tempuri.org/IMBService/loginExistsResponse")]
        SkillsAndTasksDesktopClient.MBService.Response loginExists(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/loginExists", ReplyAction="http://tempuri.org/IMBService/loginExistsResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> loginExistsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/activateByCode", ReplyAction="http://tempuri.org/IMBService/activateByCodeResponse")]
        SkillsAndTasksDesktopClient.MBService.Response activateByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/activateByCode", ReplyAction="http://tempuri.org/IMBService/activateByCodeResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> activateByCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/login", ReplyAction="http://tempuri.org/IMBService/loginResponse")]
        SkillsAndTasksDesktopClient.MBService.Response login(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/login", ReplyAction="http://tempuri.org/IMBService/loginResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> loginAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/getDatabase", ReplyAction="http://tempuri.org/IMBService/getDatabaseResponse")]
        SkillsAndTasksDesktopClient.MBService.DatabaseData getDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/getDatabase", ReplyAction="http://tempuri.org/IMBService/getDatabaseResponse")]
        System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.DatabaseData> getDatabaseAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMBServiceChannel : SkillsAndTasksDesktopClient.MBService.IMBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MBServiceClient : System.ServiceModel.ClientBase<SkillsAndTasksDesktopClient.MBService.IMBService>, SkillsAndTasksDesktopClient.MBService.IMBService {
        
        public MBServiceClient() {
        }
        
        public MBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response createAccount(SkillsAndTasksDesktopClient.MBService.User user) {
            return base.Channel.createAccount(user);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> createAccountAsync(SkillsAndTasksDesktopClient.MBService.User user) {
            return base.Channel.createAccountAsync(user);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response createSkill(SkillsAndTasksDesktopClient.MBService.Skill skill) {
            return base.Channel.createSkill(skill);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> createSkillAsync(SkillsAndTasksDesktopClient.MBService.Skill skill) {
            return base.Channel.createSkillAsync(skill);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response deleteSkill(int id) {
            return base.Channel.deleteSkill(id);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> deleteSkillAsync(int id) {
            return base.Channel.deleteSkillAsync(id);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response updateSkill(SkillsAndTasksDesktopClient.MBService.Skill skill) {
            return base.Channel.updateSkill(skill);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> updateSkillAsync(SkillsAndTasksDesktopClient.MBService.Skill skill) {
            return base.Channel.updateSkillAsync(skill);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response createTask(SkillsAndTasksDesktopClient.MBService.Task task) {
            return base.Channel.createTask(task);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> createTaskAsync(SkillsAndTasksDesktopClient.MBService.Task task) {
            return base.Channel.createTaskAsync(task);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response deleteTask(int id) {
            return base.Channel.deleteTask(id);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> deleteTaskAsync(int id) {
            return base.Channel.deleteTaskAsync(id);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response updateTask(SkillsAndTasksDesktopClient.MBService.Task task) {
            return base.Channel.updateTask(task);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> updateTaskAsync(SkillsAndTasksDesktopClient.MBService.Task task) {
            return base.Channel.updateTaskAsync(task);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response createUserSkill(SkillsAndTasksDesktopClient.MBService.UserSkill us) {
            return base.Channel.createUserSkill(us);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> createUserSkillAsync(SkillsAndTasksDesktopClient.MBService.UserSkill us) {
            return base.Channel.createUserSkillAsync(us);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response deleteUserSkill(int id) {
            return base.Channel.deleteUserSkill(id);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> deleteUserSkillAsync(int id) {
            return base.Channel.deleteUserSkillAsync(id);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response updateUserSkill(SkillsAndTasksDesktopClient.MBService.UserSkill us) {
            return base.Channel.updateUserSkill(us);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> updateUserSkillAsync(SkillsAndTasksDesktopClient.MBService.UserSkill us) {
            return base.Channel.updateUserSkillAsync(us);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response loginExists(string name) {
            return base.Channel.loginExists(name);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> loginExistsAsync(string name) {
            return base.Channel.loginExistsAsync(name);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response activateByCode(string code) {
            return base.Channel.activateByCode(code);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> activateByCodeAsync(string code) {
            return base.Channel.activateByCodeAsync(code);
        }
        
        public SkillsAndTasksDesktopClient.MBService.Response login(string name, string password) {
            return base.Channel.login(name, password);
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.Response> loginAsync(string name, string password) {
            return base.Channel.loginAsync(name, password);
        }
        
        public SkillsAndTasksDesktopClient.MBService.DatabaseData getDatabase() {
            return base.Channel.getDatabase();
        }
        
        public System.Threading.Tasks.Task<SkillsAndTasksDesktopClient.MBService.DatabaseData> getDatabaseAsync() {
            return base.Channel.getDatabaseAsync();
        }
    }
}
